### ISSUE TITLE
Error fetching image when resizing window

### ISSUE THREAD

**Issue by BenB-C** [davecparker/code12#7]
I got the following error message in JGrasp when resizing the app window:
Uncaught error fetching image:
java.lang.ClassCastException: [I cannot be cast to [B
	at java.awt.image.ColorModel.getAlpha(ColorModel.java:838)
	at java.awt.image.ColorModel.getRGB(ColorModel.java:883)
	at sun.awt.image.ImageRepresentation.convertToRGB(ImageRepresentation.java:305)
	at sun.awt.image.ImageRepresentation.setPixels(ImageRepresentation.java:569)
	at java.awt.image.AreaAveragingScaleFilter.accumPixels(AreaAveragingScaleFilter.java:213)
	at java.awt.image.AreaAveragingScaleFilter.setPixels(AreaAveragingScaleFilter.java:252)
	at sun.awt.image.ImageDecoder.setPixels(ImageDecoder.java:126)
	at sun.awt.image.PNGImageDecoder.sendPixels(PNGImageDecoder.java:558)
	at sun.awt.image.PNGImageDecoder.produceImage(PNGImageDecoder.java:478)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
![screenshot - error fetching image](https://user-images.githubusercontent.com/38901147/40432692-22518348-5e5f-11e8-87d7-1504c7d22b36.png)

I had two images at the time:

      // Set background
      ct.setHeight( 100 * 9 / 16 );
      yMax = ct.getHeight();
      ct.setBackImage( "stage.png" );
      
      // Make gun
      gun = ct.image( "gun.png", 50, 0, 8 );
      gun.y = yMax - gun.height / 2;

My first commit for Duck Hunt was done right after this happened. It's kind of hard to reproduce. I had to close and restart the app window and resize it multiple times to get the error again.

**Comment by bcauchon** [comment]
Sometimes I get the error when first running the game too (without resizing the window).

**Comment by davecparker** [comment]
Interesting, at first look it looks like a bug in Java, trying to scale this particular image file (looks like something to do with the way the transparent pixels are encoded?), but there might be something I'm doing to aggravate it.

Images are loaded asynchronously in Java, which is why the stack trace doesn't show any code12 stuff.

**Comment by bcauchon** [comment]
I think it was "stage.png" that was causing the problem.
![image](https://user-images.githubusercontent.com/38901147/40517394-f0505eda-5f69-11e8-8345-9e64b63b8cb8.png)

**Comment by bcauchon** [comment]
This image also caused the same problem:
![background](https://user-images.githubusercontent.com/38901147/40938011-5c70938a-67f5-11e8-9a36-ef68179d49e8.png)
![image](https://user-images.githubusercontent.com/38901147/40938070-8f0af1be-67f5-11e8-8f33-9f35f8dd14c2.png)
